<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Creates the qr_registration_codes table for QR-based guest registration.
     * These codes allow customers to register themselves to a project by scanning
     * a QR code generated by the admin (ügyintéző).
     */
    public function up(): void
    {
        Schema::create('qr_registration_codes', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tablo_project_id')
                ->constrained('tablo_projects')
                ->cascadeOnDelete();

            // 8 character code (e.g., ABC12345) - easy to read and type
            $table->string('code', 8)->unique();

            // Status and expiration
            $table->boolean('is_active')->default(true);
            $table->timestamp('expires_at')->nullable();

            // Usage tracking
            $table->integer('usage_count')->default(0);
            $table->integer('max_usages')->nullable(); // null = unlimited

            $table->timestamps();

            // Indexes for lookup
            $table->index('code');
            $table->index(['tablo_project_id', 'is_active']);
            $table->index('expires_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('qr_registration_codes');
    }
};
