<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class ConversionMedia extends Model implements HasMedia
{
    use InteractsWithMedia;

    /**
     * Global flag to skip conversions on upload
     * Set this to true before addMedia() to prevent automatic thumbnail generation
     */
    public static bool $skipConversions = false;

    protected $fillable = [
        'conversion_job_id',
        'folder_path',
        'conversion_status',
        'skip_initial_conversions',
        'upload_completed_at',
        'conversion_started_at',
        'conversion_completed_at',
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'skip_initial_conversions' => 'boolean',
            'upload_completed_at' => 'datetime',
            'conversion_started_at' => 'datetime',
            'conversion_completed_at' => 'datetime',
        ];
    }

    /**
     * Register media collections and conversions
     */
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('image_conversion')
            ->singleFile()
            ->useDisk('public');
    }

    /**
     * Register media conversions
     *
     * NOTE: Conversions are registered but NOT QUEUED - we handle them manually
     * in GenerateThumbnailsJob using libvips for 4-8x faster thumbnail generation.
     *
     * Registration is required for Spatie's getPath('thumb') and getUrl('thumb')
     * to work correctly - they need the conversion definition to build file paths.
     *
     * EXIF stripping and sRGB conversion are handled by ConvertImageBatchJob
     * for the original_converted version.
     */
    public function registerMediaConversions(?Media $media = null): void
    {
        // Register thumb conversion (300x300) - generated by GenerateThumbnailsJob
        // nonQueued() prevents Spatie from auto-generating, we do it manually with libvips
        $this->addMediaConversion('thumb')
            ->width(300)
            ->height(300)
            ->nonQueued();

        // Register lightbox conversion (1200x1200) - generated by GenerateThumbnailsJob
        // Named 'lightbox' instead of 'preview' to avoid watermark listener triggering
        $this->addMediaConversion('lightbox')
            ->width(1200)
            ->height(1200)
            ->nonQueued();
    }

    /**
     * Get the conversion job
     */
    public function conversionJob(): BelongsTo
    {
        return $this->belongsTo(ConversionJob::class);
    }

    /**
     * Get all media files (Spatie MediaLibrary relationship)
     * Enables eager loading for performance optimization
     */
    public function media(): MorphMany
    {
        return $this->morphMany(
            config('media-library.media_model'),
            'model'
        );
    }

    /**
     * Get thumbnail URL (300x300)
     * Returns URL if the thumbnail file physically exists
     */
    public function getThumbUrl(): ?string
    {
        $media = $this->getFirstMedia('image_conversion');

        if (!$media) {
            return null;
        }

        // Check if thumb exists physically (nonQueued conversion might complete before JSON update)
        try {
            $thumbPath = $media->getPath('thumb');
            if (file_exists($thumbPath) && filesize($thumbPath) > 0) {
                return $media->getUrl('thumb');
            }
        } catch (\Exception $e) {
            // If getPath() fails, fall back to hasGeneratedConversion check
            if ($media->hasGeneratedConversion('thumb')) {
                return $media->getUrl('thumb');
            }
        }

        return null;
    }

    /**
     * Get lightbox/preview URL (1200x1200) - NO WATERMARK
     * Returns URL if the lightbox file physically exists
     */
    public function getPreviewUrl(): ?string
    {
        $media = $this->getFirstMedia('image_conversion');

        if (!$media) {
            return null;
        }

        // Check if lightbox exists physically (nonQueued conversion might complete before JSON update)
        try {
            $lightboxPath = $media->getPath('lightbox');
            if (file_exists($lightboxPath) && filesize($lightboxPath) > 0) {
                return $media->getUrl('lightbox');
            }
        } catch (\Exception $e) {
            // If getPath() fails, fall back to hasGeneratedConversion check
            if ($media->hasGeneratedConversion('lightbox')) {
                return $media->getUrl('lightbox');
            }
        }

        return null;
    }

    /**
     * Get original converted URL (max 3000px)
     * Only returns URL if the conversion has been completed
     */
    public function getOriginalConvertedUrl(): ?string
    {
        $media = $this->getFirstMedia('image_conversion');

        // Only return URL if the conversion has been generated
        if ($media && $media->hasGeneratedConversion('original_converted')) {
            return $media->getUrl('original_converted');
        }

        return null;
    }

    /**
     * Get original filename from custom properties
     */
    public function getOriginalFilename(): ?string
    {
        $media = $this->getFirstMedia('image_conversion');

        return $media?->getCustomProperty('original_name');
    }

    /**
     * Check if upload phase is completed
     */
    public function isUploadCompleted(): bool
    {
        return ! is_null($this->upload_completed_at);
    }

    /**
     * Check if conversion phase is started
     */
    public function isConversionStarted(): bool
    {
        return ! is_null($this->conversion_started_at);
    }

    /**
     * Check if conversion phase is completed
     */
    public function isConversionCompleted(): bool
    {
        return ! is_null($this->conversion_completed_at);
    }

    /**
     * Get current phase: uploading | uploaded | converting | ready | failed
     */
    public function getPhase(): string
    {
        if ($this->conversion_status === 'failed') {
            return 'failed';
        }

        if ($this->isConversionCompleted()) {
            return 'ready';
        }

        if ($this->isConversionStarted()) {
            return 'converting';
        }

        if ($this->isUploadCompleted()) {
            return 'uploaded'; // Uploaded but conversion not started yet
        }

        return 'uploading';
    }
}
